GET  http://localhost:3002/api/get_rates/all
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###

POST http://localhost:3002/raw
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST https://www.ims.tau.ac.il/Md/Ut/Bagrut_T.aspx
content-type: application/x-www-form-urlencoded

tziun063=94&yl063=2&tziun010=97&yl010=5&tziun014=90&yl014=4&tziun020=88&yl020=2&tziun005=84&yl005=2&tziun004=92&yl004=2&tziun001=89&yl001=2&tziun016=86&yl016=5&tziun022=98&yl022=5&tziun011=90&yl011=5
#Bar Ilan Calc




