GET  http://localhost:3002/api/get_rates/all
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###

POST http://localhost:3002/raw
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:3002/alt
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###

GET https://go.huji.ac.il/jjson/huji.json?
content-type: application/json
#HUJI Calc

###

GET https://shoham.biu.ac.il/kabala/Results.aspx
Cookie: ASP.NET_SessionId=vjmqwxdplrqlyeawb554kevq
#Bar Ilan Calc

###

POST https://shoham.biu.ac.il/kabala/Psychometric.aspx
Cookie: ASP.NET_SessionId=vjmqwxdplrqlyeawb554kevq
#Bar Ilan Calc




