// Base bagrut subject inputs are enumerated in the BIU calculator.

const NUM_BY_SUBJECT = {
  0: 'bible',
  1: 'jewishThought',
  2: 'hebrew',
  3: 'literature',
  4: 'civics',
  5: 'history',
  6: 'english',
  7: 'math',
}
const SUBJECT_BY_NUM = {
  bible: 0,
  jewishThought: 1,
  hebrew: 2,
  literature: 3,
  civics: 4,
  history: 5,
  english: 6,
  math: 7,
}

const TRANSLATIONS = {
  chemistry: 'כימיה',
  architecture: 'אדריכלות ועיצוב פנים',
  cooking: 'אומנויות הבישול והאפייה המלונא',
  optics: 'אופטיקה יישומית',
  civicsThesis: 'אזרחות - עבודת גמר',
  otherWithBonus: 'אחר (כולל בונוס)',
  other1: 'אחר 1',
  other2: 'אחר_2',
  electroOptics: 'אלקטרואופטיקה',
  electronics: 'אלקטרוניקה',
  electronicsAndComputers: 'אלקטרוניקה ומחשבים',
  electronicsAndComputersThesis: 'אלקטרוניקה ומחשבים - ע. גמר',
  physics: 'פיסיקה',
  physicsThesis: 'פיסיקה - עבודת גמר',
  psychology: 'פסיכולוגיה',
  cinematography: 'אמנות הקולנוע',
  art: 'אמנות חזותית',
  biology: 'ביולוגיה',
  geography: 'גיאוגרפיה',
  agriculture: 'חקלאות',
  electricity: 'תורת החשמל',
  socialStudies: 'מדעי החברה',
  computerScience: 'מדעי המחשב',
  music: 'מוסיקה',
  automationControl: 'מערכות מכשור ובקרה',
  engineericalMechanics: 'מכניקה הנדסית',
  arabic: 'ערבית',
  french: 'צרפתית',
  talmud: 'תלמוד/תושב"ע',

  //TODO : Translate all subjects
  /*
  subject: 'אלקטרוניקה כללית ותקשורת',
  subject: 'אמנות הקולנוע-עבודת גמר',
  subject: 'אמנות התיאטרון',
  subject: 'אמנות חזותית - עבודת גמר',
  subject: 'אמנות שמושית',
  subject: 'אנגלית - עבודת גמר',
  subject: 'ארגון וניהול תעשייתי-ע.גמר',
  subject: 'בזק',
  subject: 'ביוטכנולוגיה',
  subject: 'ביולוגיה – עבודת גמר',
  subject: 'ביולוגיה חקלאית',
  subject: 'בינתחומי',
  subject: 'בקרת מכונות',
  subject: 'בקרת מכונות – עבודת גמר',
  subject: 'בקרת תהליכים',
  subject: 'גרפיקה ממוחשבת',
  subject: 'גרפיקה עצוב גרפי',
  subject: 'דת האסלם',
  subject: 'דת נוצרית',
  subject: 'הבעה עברית לעולה',
  subject: 'הגות מדינית',
  subject: 'הגנת סייבר',
  subject: 'הגנת סייבר – עבודת גמר',
  subject: 'הדפסת אופסט',
  subject: 'החנוך בגיל הרך',
  subject: 'המטוס ומערכותיו',
  subject: 'המסוק ומערכותיו',
  subject: 'הסטוריה – עבודת גמר',
  subject: 'הפקות בתקשורת- עבודת גמר',
  subject: 'חוק ומשפט ',
  subject: 'חוק ומשפט – עבודת גמר',
  subject: 'חינוך גופני',
  subject: 'חינוך גופני וביולוגיה',
  subject: 'חישוב סטטיסטיקה וקונסטרוקציות',
  subject: 'חקלאות - עבודת גמר',
  subject: 'חשבונאות',
  subject: 'טכנולוגיה מוכללת',
  subject: 'טכנולוגיה מוכללת-עבודת גמר',
  subject: 'טכנולוגיות בנייה',
  subject: 'טלוויזיה וקולנוע',
  subject: 'טלקומוניקציה',
  subject: 'יהדות ממ"ד',
  subject: 'יישומי פעילויות בחינוך',
  subject: 'יישומי פעילויות בחינוך – ע.גמר',
  subject: 'יישומים בביוטכנולוגיה',
  subject: 'יישומים בביוטכנולוגיה – ע. גמר',
  subject: 'ימאות / חובלות',
  subject: 'ימאות ומטאורולוגיה',
  subject: 'ימאות וספינות',
  subject: 'יסודות תורת המחשב',
  subject: 'כימיה',
  subject: 'כימיה – עבודת גמר',
  subject: 'כימיה וטכסטיל',
  subject: 'כימיה טכנולוגית',
  subject: 'כלכלה',
  subject: 'כלכלה  הנדסית ',
  subject: 'כלכלה  הנדסית – עבודת גמר',
  subject: 'כתבנות',
  subject: 'לימודי ארץ ישראל',
  subject: 'לימודי הסביבה (אקולוגיה)',
  subject: 'לימודי הסביבה (אקולוגיה) – עבו',
  subject: "מבוא למדע וטכנו' לכל ",
  subject: 'מדע וטכנולוגיה בחברה',
  subject: 'מדע וטכנולוגיה לכל',
  subject: 'מדע חישובי',
  subject: 'מדע כדור הארץ (גאולוגיה)',
  subject: 'מדעי הבריאות',
  subject: 'מדעי ההנדסה',
  subject: 'מדעי החברה - חוק ומשפט',
  subject: 'מדעי החברה - עבודת גמר',
  subject: 'מדעי החיים והחקלאות',
  subject: 'מדעי החיים וחקלאות - עבודת גמר',
  subject: 'מדעי הטכנולוגיה',
  subject: 'מדעי הים',
  subject: 'מדעי המדינה',
  subject: 'מדעי המחשב- ע. גמר',
  subject: 'מוזיקה – עבודת גמר ',
  subject: 'מורשת הדרוזים',
  subject: 'מזכירות',
  subject: 'מזכירות ומנהל',
  subject: 'מחול',
  subject: 'מחול - ע. גמר',
  subject: 'מחשבים ומערכות',
  subject: 'מחשבים ומערכות - ע. גמר',
  subject: 'מחשבת ישראל - עבודת גמר',
  subject: 'מחשוב ובקרה – עבודת גמר',
  subject: 'מידע וידע באינטרנט',
  subject: 'מיחשוב ובקרה',
  subject: 'מיכון חקלאי ומערכות',
  subject: 'מינהל',
  subject: 'מיקרוביולוגיה',
  subject: 'מכונות חום ותרמודינמיקה',
  subject: 'מכונות חקלאיות וטקטורים',
  subject: 'מכטרוניקה',
  subject: 'מכטרוניקיה - ע. גמר',
  subject: 'מכניקה',
  subject: 'מכשור בקרה ומחשבים',
  subject: 'מכשור ובקרה בהתישבות',
  subject: 'מכשירים ופיקוד',
  subject: 'מנהל וכלכלה',
  subject: 'מנועי מטוסים ותרמודינמיקה',
  subject: "מע' אלקט' וחשמל",
  subject: 'מערכות אלקטרואופטיות',
  subject: 'מערכות אלקטרוניות',
  subject: 'מערכות אלקטרוניות-עבודת גמר',
  subject: 'מערכות ביוטכנולוגיה – ע.גמר',
  subject: 'מערכות ביוטכנולוגיות',
  subject: 'מערכות בקרת תהליכים',
  subject: 'מערכות חשמל',
  subject: 'מערכות מדענות ממוחשבות',
  subject: 'מערכות מכונאות רכב',
  subject: 'מערכות פיקוד ובקרה',
  subject: 'מערכות פיקוד ובקרה- ע.גמר',
  subject: 'מערכות רפואיות ',
  subject: 'מערכות רפואיות – עבודת גמר',
  subject: 'מערכות תוכנה וחומרה',
  subject: 'מערכות תיב"מ',
  subject: 'מערכות תיב"מ - ע. גמר',
  subject: 'מערכות תכנון וייצור',
  subject: 'מערכות תעופה',
  subject: 'מערכות תקשוב',
  subject: 'מערכות תקשורת ומיתוג',
  subject: 'מקצוע בין תחומי',
  subject: 'מתמטיקה – עבודת גמר',
  subject: 'ניהול',
  subject: 'ניהול הייצור',
  subject: 'ניהול הייצור – עבודת גמר',
  subject: 'ניהול התפעול',
  subject: 'ניהול התפעול - ע. גמר',
  subject: 'ניהול ומלאי',
  subject: 'ניהול חשבונות ממוחשב',
  subject: 'ניהול מלונאי',
  subject: 'ניהול משאבי אנוש',
  subject: 'ניהול משאבי אנוש - ע. גמר',
  subject: 'ניהול שיווק ומכירות – עבודת גמ',
  subject: 'ניתוח ואיתור מידע דיגיטלי',
  subject: 'ניתוח מערכות וארגון קבצים',
  subject: 'סטטיסטיקה',
  subject: 'סינית',
  subject: 'סיעוד כללי',
  subject: 'ספרות -  עבודת גמר',
  subject: 'ספרות התיאטרון',
  subject: 'ספרות ומחשבת ישראל',
  subject: 'ספרות ילדים',
  subject: 'עבוד נתונים אוטומטי',
  subject: 'עבודת גמר',
  subject: 'עברית לדרוזים',
  subject: 'עברית לערבים',
  subject: 'עולם הערבים והאיסלם',
  subject: 'עיבוד נתונים אוטומטי',
  subject: 'עיצוב גרפי',
  subject: 'עיצוב וטיפוח החן',
  subject: 'עיצוב חזותי',
  subject: 'עיצוב כללי',
  subject: 'עם ועלם',
  subject: 'עצוב',
  subject: 'עצוב – עבודת גמר',
  subject: 'עצוב אופנה ותלבושות',
  subject: 'עצוב אופנה ותלבושות - ע. גמר',
  subject: 'ערבית - עבודת גמר',
  subject: 'ערבית לדרוזים',
  subject: 'ערבית לערבים',
  subject: 'פ"ג במע\' מידע וידע',
  subject: 'פ"ג במע\' מידע וידע -ע.גמר',
  subject: 'פ. מכונות ח. חומרים',
  subject: 'פילוסופיה',
  subject: 'פילוסופיה- עבודת גמר',

  subject: 'פסיכולוגיה התפתחותית',
  subject: 'צילום',
  subject: 'קבלת תיירות',
  subject: 'קולנוע',
  subject: 'קירור ומיזוג אויר',
  subject: 'רדיו ואלקטרוניקה ימית',
  subject: 'שווק וקדום מכירות – עבודת גמר',
  subject: 'שיווק וקידום מכירות',
  subject: 'שפה זרה',
  subject: 'שרטוט',
  subject: 'שרטוט טכני',
  subject: 'תולדות האומנות',
  subject: 'תולדות הלבוש וציורו',
  subject: 'תולדות הערבים',
  subject: 'תולדות הערבים והאיסלם',
  subject: 'תולדות התאטרון',
  subject: 'תולדות עם ישראל',
  subject: 'תולדות עם ישראל - בי"ס דתי',
  subject: 'תולדות עם ישראל ואזרחות',
  subject: 'תורת הניווט הימי',
  subject: 'תורת הסעוד',
  subject: 'תחזוקת מערכות מכניות',
  subject: 'תיאטרון',
  subject: 'תיאטרון - עבודת גמר',
  subject: 'תיירות',
  subject: 'תיירות ותפעול',
  subject: 'תכנה וחמרה',
  subject: 'תכנון הנדסי של מבנים',
  subject: 'תכנון הנדסי של מבנים – עבודת ג',
  subject: 'תכנון ותכנות מערכות',
  subject: 'תכנון ותכנות מערכות-עבודת גמר',
  subject: 'תכנון פרקי מכונות',
  subject: 'תכשיטנות עצוב וטכנולוגיה',
  subject: 'תנ"ך - ע. גמר',
  subject: 'תנ"ך - עבודת גמר',
  subject: 'תעשיה כימית',
  subject: 'תקשורת',
  subject: 'תקשורת בינלאומית (באנגלית)',
  subject: 'תקשורת המונים',
  subject: 'תקשורת וחברה',
  subject: 'תרמודינמיקה',
  subject: 'תרמודינמיקה טכנית',
  subject: 'תרמודינמיקה טכנית – עבודת גמר',
  subject: 'תשתיות מחשוב ותקשוב',
  subject: 'תשתיות מחשוב ותקשוב - ע. גמר',
  */
}

export { SUBJECT_BY_NUM, NUM_BY_SUBJECT, TRANSLATIONS }
