export default {
  אדריכלות: {
    Id: 2542,
    Year: 2023,
    SubjectID: 812,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אדריכלות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אדריכלות ועצוב נוף': {
    Id: 2541,
    Year: 2023,
    SubjectID: 811,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אדריכלות ועצוב נוף',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אומנויות הבישול והאפייה המלונאית': {
    Id: 2543,
    Year: 2023,
    SubjectID: 813,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אומנויות הבישול והאפייה המלונאית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אומנות שימושית': {
    Id: 2546,
    Year: 2023,
    SubjectID: 816,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אומנות שימושית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אופטיקה יישומית': {
    Id: 2544,
    Year: 2023,
    SubjectID: 814,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אופטיקה יישומית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  אזרחות: {
    Id: 2335,
    Year: 2023,
    SubjectID: 24,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אזרחות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  איטלקית: {
    Id: 2506,
    Year: 2023,
    SubjectID: 571,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'איטלקית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  אלקטרוניקה: {
    Id: 2364,
    Year: 2023,
    SubjectID: 53,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אלקטרוניקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אלקטרוניקה ומחשבים': {
    Id: 2545,
    Year: 2023,
    SubjectID: 815,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אלקטרוניקה ומחשבים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  אמהרית: {
    Id: 2507,
    Year: 2023,
    SubjectID: 572,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אמהרית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אמנות הקולנוע': {
    Id: 2368,
    Year: 2023,
    SubjectID: 61,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אמנות הקולנוע',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אמנות חזותית': {
    Id: 2362,
    Year: 2023,
    SubjectID: 50,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אמנות חזותית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  אנגלית: {
    Id: 2327,
    Year: 2023,
    SubjectID: 16,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אנגלית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'אפסנאות וטכנולוגיה': {
    Id: 2421,
    Year: 2023,
    SubjectID: 245,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'אפסנאות וטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  בולגרית: {
    Id: 2521,
    Year: 2023,
    SubjectID: 588,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'בולגרית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  בזק: {
    Id: 2548,
    Year: 2023,
    SubjectID: 818,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'בזק',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  ביוטכנולוגיה: {
    Id: 2454,
    Year: 2023,
    SubjectID: 283,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ביוטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  ביוכימיה: {
    Id: 2526,
    Year: 2023,
    SubjectID: 789,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ביוכימיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  ביולוגיה: {
    Id: 2354,
    Year: 2023,
    SubjectID: 43,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ביולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ביולוגיה חקלאית': {
    Id: 2357,
    Year: 2023,
    SubjectID: 45,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ביולוגיה חקלאית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ביולוגיה לקוסמטיקה': {
    Id: 2413,
    Year: 2023,
    SubjectID: 235,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ביולוגיה לקוסמטיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'בקרת אקלים': {
    Id: 2601,
    Year: 2023,
    SubjectID: 874,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'בקרת אקלים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'בקרת מכונות': {
    Id: 2549,
    Year: 2023,
    SubjectID: 819,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'בקרת מכונות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'בקרת תהליכים': {
    Id: 2456,
    Year: 2023,
    SubjectID: 287,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'בקרת תהליכים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'בריאות הילד וסביבתו': {
    Id: 2409,
    Year: 2023,
    SubjectID: 230,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'בריאות הילד וסביבתו',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'גאוגרפיה אדם וסביבה': {
    Id: 2366,
    Year: 2023,
    SubjectID: 57,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'גאוגרפיה אדם וסביבה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'גלוף עץ עצוב וטכנולוגיה': {
    Id: 2469,
    Year: 2023,
    SubjectID: 303,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'גלוף עץ עצוב וטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  גרוזית: {
    Id: 2508,
    Year: 2023,
    SubjectID: 573,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'גרוזית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  גרמנית: {
    Id: 2509,
    Year: 2023,
    SubjectID: 574,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'גרמנית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'גרפיקה ממוחשבת': {
    Id: 2550,
    Year: 2023,
    SubjectID: 820,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'גרפיקה ממוחשבת',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'גרפיקה עצוב גרפי': {
    Id: 2428,
    Year: 2023,
    SubjectID: 253,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'גרפיקה עצוב גרפי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'גרפיקה עצוב וטכנולוגיה': {
    Id: 2429,
    Year: 2023,
    SubjectID: 254,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'גרפיקה עצוב וטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'דיפלומטיה ותקשורת בינלאומית': {
    Id: 2631,
    Year: 2023,
    SubjectID: 91,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'דיפלומטיה ותקשורת בינלאומית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'דת האסלם': {
    Id: 2379,
    Year: 2023,
    SubjectID: 74,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'דת האסלם',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הגנת סייבר': {
    Id: 2634,
    Year: 2023,
    SubjectID: 782,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הגנת סייבר',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הדפסת אופסט': {
    Id: 2476,
    Year: 2023,
    SubjectID: 821,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הדפסת אופסט',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  הולנדית: {
    Id: 2510,
    Year: 2023,
    SubjectID: 575,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הולנדית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  הונגרית: {
    Id: 2511,
    Year: 2023,
    SubjectID: 576,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הונגרית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  היסטוריה: {
    Id: 2333,
    Year: 2023,
    SubjectID: 22,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'היסטוריה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'המטוס ומערכותיו': {
    Id: 2461,
    Year: 2023,
    SubjectID: 295,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'המטוס ומערכותיו',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'המסוק ומערכותיו': {
    Id: 2388,
    Year: 2023,
    SubjectID: 206,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'המסוק ומערכותיו',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הנדסת אוטוטק': {
    Id: 2654,
    Year: 2023,
    SubjectID: 774,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הנדסת אוטוטק',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הסטוריה ואזרחות': {
    Id: 2486,
    Year: 2023,
    SubjectID: 480,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הסטוריה ואזרחות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הסטוריה וגאוגרפיה': {
    Id: 2487,
    Year: 2023,
    SubjectID: 481,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הסטוריה וגאוגרפיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הסטוריה ותולדות הערבים': {
    Id: 2488,
    Year: 2023,
    SubjectID: 482,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הסטוריה ותולדות הערבים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הסטוריה ותולדות הערבים ואזרחות': {
    Id: 2489,
    Year: 2023,
    SubjectID: 483,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הסטוריה ותולדות הערבים ואזרחות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הסטוריה ותע"י': {
    Id: 2490,
    Year: 2023,
    SubjectID: 484,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הסטוריה ותע"י',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הסטוריה תע"י ואזרחות': {
    Id: 2491,
    Year: 2023,
    SubjectID: 485,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הסטוריה תע"י ואזרחות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'הפקות בתקשורת': {
    Id: 2589,
    Year: 2023,
    SubjectID: 862,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'הפקות בתקשורת',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'השפעה ויוזמה חברתית': {
    Id: 2652,
    Year: 2023,
    SubjectID: 779,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'השפעה ויוזמה חברתית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חבור עברי': {
    Id: 2324,
    Year: 2023,
    SubjectID: 13,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חבור עברי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חוק ומשפט': {
    Id: 2377,
    Year: 2023,
    SubjectID: 72,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חוק ומשפט',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חינוך גופני': {
    Id: 2352,
    Year: 2023,
    SubjectID: 41,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חינוך גופני',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חנוך גופני וביולוגיה': {
    Id: 2493,
    Year: 2023,
    SubjectID: 487,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חנוך גופני וביולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חנוך הילד בגיל הרך': {
    Id: 2408,
    Year: 2023,
    SubjectID: 229,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חנוך הילד בגיל הרך',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  חקלאות: {
    Id: 2358,
    Year: 2023,
    SubjectID: 46,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חקלאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  חשבונאות: {
    Id: 2552,
    Year: 2023,
    SubjectID: 824,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חשבונאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חשוב סטטי וקונסטרוקציות': {
    Id: 2434,
    Year: 2023,
    SubjectID: 261,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חשוב סטטי וקונסטרוקציות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חשובי קונסטרוקציות': {
    Id: 2435,
    Year: 2023,
    SubjectID: 262,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חשובי קונסטרוקציות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חשמל ואלקטרוניקה ברכב': {
    Id: 2459,
    Year: 2023,
    SubjectID: 293,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חשמל ואלקטרוניקה ברכב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'חשמל ובקרה ימיים': {
    Id: 2553,
    Year: 2023,
    SubjectID: 825,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'חשמל ובקרה ימיים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכלוגיה ובדיקת מזון': {
    Id: 2480,
    Year: 2023,
    SubjectID: 313,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכלוגיה ובדיקת מזון',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכנאות שיניים': {
    Id: 2554,
    Year: 2023,
    SubjectID: 826,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכנאות שיניים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכנולוגיה מוכללת': {
    Id: 2621,
    Year: 2023,
    SubjectID: 895,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכנולוגיה מוכללת',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכנולוגיה של הדפוס': {
    Id: 2440,
    Year: 2023,
    SubjectID: 267,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכנולוגיה של הדפוס',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכנולוגיה של הקולנוע והטלויזיה': {
    Id: 2474,
    Year: 2023,
    SubjectID: 308,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכנולוגיה של הקולנוע והטלויזיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכנולוגיה של טכנאות שיניים': {
    Id: 2418,
    Year: 2023,
    SubjectID: 242,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכנולוגיה של טכנאות שיניים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכנולוגיות בנייה': {
    Id: 2540,
    Year: 2023,
    SubjectID: 810,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכנולוגיות בנייה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טכנולוגית בנייה': {
    Id: 2555,
    Year: 2023,
    SubjectID: 827,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טכנולוגית בנייה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טלוויזיה וקולנוע': {
    Id: 2556,
    Year: 2023,
    SubjectID: 828,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טלוויזיה וקולנוע',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'טפול בחולה פנימי ובחולה כירורג': {
    Id: 2415,
    Year: 2023,
    SubjectID: 237,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'טפול בחולה פנימי ובחולה כירורג',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ידיעת העם והמדינה': {
    Id: 2342,
    Year: 2023,
    SubjectID: 31,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ידיעת העם והמדינה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  יהדות: {
    Id: 2315,
    Year: 2023,
    SubjectID: 4,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יהדות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'יהדות ממ"ד': {
    Id: 2381,
    Year: 2023,
    SubjectID: 77,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יהדות ממ"ד',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  יידיש: {
    Id: 2505,
    Year: 2023,
    SubjectID: 570,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יידיש',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ייצור רהיטים ונגרות בניין': {
    Id: 2557,
    Year: 2023,
    SubjectID: 829,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ייצור רהיטים ונגרות בניין',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'יישומי אוטוטק': {
    Id: 2653,
    Year: 2023,
    SubjectID: 775,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יישומי אוטוטק',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'יישומי ביוטכנולוגיה': {
    Id: 2635,
    Year: 2023,
    SubjectID: 783,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יישומי ביוטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'יישומי מחשב': {
    Id: 2646,
    Year: 2023,
    SubjectID: 993,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יישומי מחשב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'יישומי פעילויות בחינוך': {
    Id: 2531,
    Year: 2023,
    SubjectID: 797,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יישומי פעילויות בחינוך',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  ימאות: {
    Id: 2558,
    Year: 2023,
    SubjectID: 830,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ימאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ימאות ומטאורולוגיה': {
    Id: 2477,
    Year: 2023,
    SubjectID: 310,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ימאות ומטאורולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ימאות וספינות': {
    Id: 2533,
    Year: 2023,
    SubjectID: 801,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ימאות וספינות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'יסודות בעיצוב שיער': {
    Id: 2649,
    Year: 2023,
    SubjectID: 778,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יסודות בעיצוב שיער',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'יסודות תורת המחשב': {
    Id: 2353,
    Year: 2023,
    SubjectID: 42,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'יסודות תורת המחשב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  כימיה: {
    Id: 2348,
    Year: 2023,
    SubjectID: 37,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כימיה אנליטית ותורת המכשירים': {
    Id: 2448,
    Year: 2023,
    SubjectID: 277,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה אנליטית ותורת המכשירים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כימיה וביולוגיה': {
    Id: 2453,
    Year: 2023,
    SubjectID: 282,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה וביולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כימיה וטכסטיל': {
    Id: 2410,
    Year: 2023,
    SubjectID: 232,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה וטכסטיל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כימיה טכנולוגית': {
    Id: 2559,
    Year: 2023,
    SubjectID: 831,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה טכנולוגית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כימיה כללית ואורגנית': {
    Id: 2451,
    Year: 2023,
    SubjectID: 279,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה כללית ואורגנית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כימיה כללית ואנאורגנית': {
    Id: 2450,
    Year: 2023,
    SubjectID: 278,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה כללית ואנאורגנית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כימיה לקוסמטיקה': {
    Id: 2414,
    Year: 2023,
    SubjectID: 236,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כימיה לקוסמטיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  כלכלה: {
    Id: 2370,
    Year: 2023,
    SubjectID: 63,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כלכלה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'כלכלה ומשק': {
    Id: 2615,
    Year: 2023,
    SubjectID: 888,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כלכלה ומשק',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  כתבנות: {
    Id: 2484,
    Year: 2023,
    SubjectID: 317,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'כתבנות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  לאדינו: {
    Id: 2520,
    Year: 2023,
    SubjectID: 587,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'לאדינו',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'לטינית /רומית': {
    Id: 2512,
    Year: 2023,
    SubjectID: 577,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'לטינית /רומית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'לימודי ארץ ישראל וארכיאולוגיה': {
    Id: 2323,
    Year: 2023,
    SubjectID: 12,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'לימודי ארץ ישראל וארכיאולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'לשון ותקשורת': {
    Id: 2374,
    Year: 2023,
    SubjectID: 67,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'לשון ותקשורת',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מבוא למחשבים וענ"א': {
    Id: 2395,
    Year: 2023,
    SubjectID: 213,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מבוא למחשבים וענ"א',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מבוא למחשבים ותכנות': {
    Id: 2402,
    Year: 2023,
    SubjectID: 222,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מבוא למחשבים ותכנות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדע התזונה והארוח': {
    Id: 2404,
    Year: 2023,
    SubjectID: 225,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדע התזונה והארוח',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדע וטכנולוגיה לכל': {
    Id: 2628,
    Year: 2023,
    SubjectID: 704,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדע וטכנולוגיה לכל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדע חישובי': {
    Id: 2524,
    Year: 2023,
    SubjectID: 703,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדע חישובי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי הבריאות': {
    Id: 2534,
    Year: 2023,
    SubjectID: 802,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי הבריאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי ההנדסה': {
    Id: 2537,
    Year: 2023,
    SubjectID: 807,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי ההנדסה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי החברה': {
    Id: 2361,
    Year: 2023,
    SubjectID: 49,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי החברה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי החיים וחקלאות': {
    Id: 2355,
    Year: 2023,
    SubjectID: 44,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי החיים וחקלאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי הטכנולוגיה': {
    Id: 2620,
    Year: 2023,
    SubjectID: 894,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי הטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי הים': {
    Id: 2532,
    Year: 2023,
    SubjectID: 800,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי הים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי המדינה': {
    Id: 2373,
    Year: 2023,
    SubjectID: 66,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי המדינה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי המחשב': {
    Id: 2625,
    Year: 2023,
    SubjectID: 899,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי המחשב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי הנדסה': {
    Id: 2622,
    Year: 2023,
    SubjectID: 896,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי הנדסה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי הסביבה': {
    Id: 2371,
    Year: 2023,
    SubjectID: 64,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי הסביבה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי התזונה': {
    Id: 2643,
    Year: 2023,
    SubjectID: 798,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי התזונה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי כדור הארץ': {
    Id: 2369,
    Year: 2023,
    SubjectID: 62,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי כדור הארץ',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מדעי תחבורה מתקדמת': {
    Id: 2648,
    Year: 2023,
    SubjectID: 776,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מדעי תחבורה מתקדמת',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מוט"ב_- מדע וטכנולוגיה בחברה': {
    Id: 2367,
    Year: 2023,
    SubjectID: 60,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מוט"ב_- מדע וטכנולוגיה בחברה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  מוסיקה: {
    Id: 2360,
    Year: 2023,
    SubjectID: 48,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מוסיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מורשת דרוזית': {
    Id: 2338,
    Year: 2023,
    SubjectID: 27,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מורשת דרוזית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מורשת דת נוצרית': {
    Id: 2378,
    Year: 2023,
    SubjectID: 73,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מורשת דת נוצרית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מורשת ודת האסלאם': {
    Id: 2359,
    Year: 2023,
    SubjectID: 47,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מורשת ודת האסלאם',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מורשת, דת ותרבות במזרח התיכון ': {
    Id: 2640,
    Year: 2023,
    SubjectID: 503,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מורשת דת ותרבות במזרח התיכון',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  מזכירות: {
    Id: 2483,
    Year: 2023,
    SubjectID: 316,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מזכירות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מזכירות ומנהל': {
    Id: 2419,
    Year: 2023,
    SubjectID: 243,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מזכירות ומנהל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  מחול: {
    Id: 2375,
    Year: 2023,
    SubjectID: 68,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מחול',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מחשבים ומערכות': {
    Id: 2561,
    Year: 2023,
    SubjectID: 833,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מחשבים ומערכות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מחשבת ישראל': {
    Id: 2349,
    Year: 2023,
    SubjectID: 38,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מחשבת ישראל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מחשבת ישראל וספרות': {
    Id: 2500,
    Year: 2023,
    SubjectID: 497,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מחשבת ישראל וספרות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מחשוב ובקרה': {
    Id: 2562,
    Year: 2023,
    SubjectID: 834,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מחשוב ובקרה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מחשוב ובקרה בהתיישבות': {
    Id: 2563,
    Year: 2023,
    SubjectID: 835,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מחשוב ובקרה בהתיישבות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מידע וידע באינטרנט': {
    Id: 2637,
    Year: 2023,
    SubjectID: 785,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מידע וידע באינטרנט',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מיכון חקלאי ומערכות': {
    Id: 2464,
    Year: 2023,
    SubjectID: 298,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מיכון חקלאי ומערכות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  מיקרוביולוגיה: {
    Id: 2564,
    Year: 2023,
    SubjectID: 836,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מיקרוביולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מכונאות ימית': {
    Id: 2565,
    Year: 2023,
    SubjectID: 837,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מכונאות ימית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מכונאות כללית': {
    Id: 2391,
    Year: 2023,
    SubjectID: 209,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מכונאות כללית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מכונאות מיכון': {
    Id: 2455,
    Year: 2023,
    SubjectID: 285,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מכונאות מיכון',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מכונות חום ותרמודנמיקה': {
    Id: 2384,
    Year: 2023,
    SubjectID: 202,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מכונות חום ותרמודנמיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מכונות חקלאיות וטרקטורים': {
    Id: 2466,
    Year: 2023,
    SubjectID: 300,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מכונות חקלאיות וטרקטורים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מכניקה הנדסית': {
    Id: 2566,
    Year: 2023,
    SubjectID: 838,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מכניקה הנדסית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מכשירים ופיקוד': {
    Id: 2482,
    Year: 2023,
    SubjectID: 315,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מכשירים ופיקוד',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מנהיגות ויזמות': {
    Id: 2644,
    Year: 2023,
    SubjectID: 799,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מנהיגות ויזמות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מנהל וכלכלה': {
    Id: 2492,
    Year: 2023,
    SubjectID: 839,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מנהל וכלכלה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מנועי מטוסים ותרמודנמיקה': {
    Id: 2462,
    Year: 2023,
    SubjectID: 296,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מנועי מטוסים ותרמודנמיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מנועים ומערכות הדראוליות': {
    Id: 2458,
    Year: 2023,
    SubjectID: 291,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מנועים ומערכות הדראוליות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  "מער' אלק' וחשמל ברכב": {
    Id: 2525,
    Year: 2023,
    SubjectID: 787,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: "מער' אלק' וחשמל ברכב",
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות אוטוטק': {
    Id: 2638,
    Year: 2023,
    SubjectID: 786,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות אוטוטק',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות אלקטואופטיות': {
    Id: 2567,
    Year: 2023,
    SubjectID: 840,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות אלקטואופטיות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות אלקטרוניות': {
    Id: 2568,
    Year: 2023,
    SubjectID: 841,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות אלקטרוניות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות בזק': {
    Id: 2397,
    Year: 2023,
    SubjectID: 216,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות בזק',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות ביוטכנולוגיה': {
    Id: 2569,
    Year: 2023,
    SubjectID: 842,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות ביוטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות בקרה ממוחשבות': {
    Id: 2403,
    Year: 2023,
    SubjectID: 224,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות בקרה ממוחשבות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות ומכונאות בחקלאות': {
    Id: 2465,
    Year: 2023,
    SubjectID: 299,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות ומכונאות בחקלאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות חשמל': {
    Id: 2572,
    Year: 2023,
    SubjectID: 845,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות חשמל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות חשמל ובקרה ימיות': {
    Id: 2400,
    Year: 2023,
    SubjectID: 220,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות חשמל ובקרה ימיות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות חשמל רכב': {
    Id: 2576,
    Year: 2023,
    SubjectID: 849,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות חשמל רכב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות כח ועבודה': {
    Id: 2390,
    Year: 2023,
    SubjectID: 208,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות כח ועבודה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות מדענות ממוחשבות': {
    Id: 2609,
    Year: 2023,
    SubjectID: 882,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות מדענות ממוחשבות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות מומחה': {
    Id: 2574,
    Year: 2023,
    SubjectID: 847,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות מומחה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות מידע וידע': {
    Id: 2629,
    Year: 2023,
    SubjectID: 790,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות מידע וידע',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות מכון חקלאי': {
    Id: 2573,
    Year: 2023,
    SubjectID: 846,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות מכון חקלאי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות מכונאות רכב': {
    Id: 2596,
    Year: 2023,
    SubjectID: 869,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות מכונאות רכב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות מכטרוניקה': {
    Id: 2356,
    Year: 2023,
    SubjectID: 805,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות מכטרוניקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות מכשור ובקרה': {
    Id: 2479,
    Year: 2023,
    SubjectID: 312,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות מכשור ובקרה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות ניהול מלונאי': {
    Id: 2600,
    Year: 2023,
    SubjectID: 873,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות ניהול מלונאי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות סיב"ם': {
    Id: 2623,
    Year: 2023,
    SubjectID: 897,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות סיב"ם',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות פיקוד ובקרה': {
    Id: 2575,
    Year: 2023,
    SubjectID: 848,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות פיקוד ובקרה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות פקוד ובקרה - מחשבים': {
    Id: 2399,
    Year: 2023,
    SubjectID: 219,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות פקוד ובקרה - מחשבים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות צ.מ.ה - ציוד מכני הנדסי': {
    Id: 2632,
    Year: 2023,
    SubjectID: 780,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות צ.מ.ה - ציוד מכני הנדסי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות רפואיות': {
    Id: 2536,
    Year: 2023,
    SubjectID: 806,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות רפואיות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות תוכנה וחמרה': {
    Id: 2401,
    Year: 2023,
    SubjectID: 221,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות תוכנה וחמרה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות תיב"מ': {
    Id: 2577,
    Year: 2023,
    SubjectID: 850,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות תיב"מ',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות תכנון וייצור': {
    Id: 2579,
    Year: 2023,
    SubjectID: 852,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות תכנון וייצור',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות תעופה': {
    Id: 2580,
    Year: 2023,
    SubjectID: 853,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות תעופה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות תעופה ואביזראות מטוסים': {
    Id: 2386,
    Year: 2023,
    SubjectID: 204,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות תעופה ואביזראות מטוסים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות תקשוב': {
    Id: 2527,
    Year: 2023,
    SubjectID: 791,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות תקשוב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכות תקשורת': {
    Id: 2398,
    Year: 2023,
    SubjectID: 217,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכות תקשורת',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מערכת תעוש הבגד': {
    Id: 2578,
    Year: 2023,
    SubjectID: 851,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מערכת תעוש הבגד',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'מקצוע בין תחומי': {
    Id: 2382,
    Year: 2023,
    SubjectID: 95,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מקצוע בין תחומי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  מתמטיקה: {
    Id: 2346,
    Year: 2023,
    SubjectID: 35,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'מתמטיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'נהול התפעול': {
    Id: 2539,
    Year: 2023,
    SubjectID: 809,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'נהול התפעול',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'נהול ומזכירות': {
    Id: 2581,
    Year: 2023,
    SubjectID: 854,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'נהול ומזכירות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'נהול מוסד ומחסנאות': {
    Id: 2405,
    Year: 2023,
    SubjectID: 226,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'נהול מוסד ומחסנאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'נהול רכש ומלאי': {
    Id: 2420,
    Year: 2023,
    SubjectID: 244,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'נהול רכש ומלאי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'נהול שווק ומכירות': {
    Id: 2583,
    Year: 2023,
    SubjectID: 856,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'נהול שווק ומכירות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ניהול הייצור': {
    Id: 2645,
    Year: 2023,
    SubjectID: 804,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ניהול הייצור',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ניהול התפעול': {
    Id: 2535,
    Year: 2023,
    SubjectID: 803,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ניהול התפעול',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ניהול ומלאי': {
    Id: 2599,
    Year: 2023,
    SubjectID: 872,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ניהול ומלאי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ניהול מלונאי': {
    Id: 2619,
    Year: 2023,
    SubjectID: 893,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ניהול מלונאי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ניהול משאבי אנוש': {
    Id: 2538,
    Year: 2023,
    SubjectID: 808,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ניהול משאבי אנוש',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ניהול תיירותי': {
    Id: 2604,
    Year: 2023,
    SubjectID: 877,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ניהול תיירותי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ניתוח ואיתור מידע דיגיטלי': {
    Id: 2636,
    Year: 2023,
    SubjectID: 784,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ניתוח ואיתור מידע דיגיטלי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'נתוח מערכות וארגון קבצים': {
    Id: 2584,
    Year: 2023,
    SubjectID: 857,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'נתוח מערכות וארגון קבצים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סדר דפוס': {
    Id: 2585,
    Year: 2023,
    SubjectID: 858,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סדר דפוס',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  סוציולוגיה: {
    Id: 2372,
    Year: 2023,
    SubjectID: 65,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סוציולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סייעות ברפואת שיניים': {
    Id: 2416,
    Year: 2023,
    SubjectID: 239,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סייעות ברפואת שיניים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  סינית: {
    Id: 2523,
    Year: 2023,
    SubjectID: 702,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סינית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  סלובקית: {
    Id: 2513,
    Year: 2023,
    SubjectID: 578,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סלובקית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סעוד כללי': {
    Id: 2586,
    Year: 2023,
    SubjectID: 859,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סעוד כללי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  ספרדית: {
    Id: 2514,
    Year: 2023,
    SubjectID: 579,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ספרדית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  ספרות: {
    Id: 2319,
    Year: 2023,
    SubjectID: 8,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ספרות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ספרות ופילוסופיה': {
    Id: 2495,
    Year: 2023,
    SubjectID: 492,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ספרות ופילוסופיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ספרות ותושבע"פ': {
    Id: 2496,
    Year: 2023,
    SubjectID: 493,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ספרות ותושבע"פ',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ספרות ילדים': {
    Id: 2588,
    Year: 2023,
    SubjectID: 861,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ספרות ילדים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  סרבית: {
    Id: 2522,
    Year: 2023,
    SubjectID: 589,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרבית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט אדריכלי': {
    Id: 2438,
    Year: 2023,
    SubjectID: 265,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט אדריכלי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט אוטומציה וחשמל': {
    Id: 2457,
    Year: 2023,
    SubjectID: 288,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט אוטומציה וחשמל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט בניין אדריכלי': {
    Id: 2437,
    Year: 2023,
    SubjectID: 264,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט בניין אדריכלי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט בניין לקונסטרוקציות': {
    Id: 2436,
    Year: 2023,
    SubjectID: 263,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט בניין לקונסטרוקציות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט ואווירודנמיקה': {
    Id: 2463,
    Year: 2023,
    SubjectID: 297,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט ואווירודנמיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט וטכנולוגיה': {
    Id: 2443,
    Year: 2023,
    SubjectID: 271,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט וטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט וטכנולוגיה במיכון חקלאי': {
    Id: 2481,
    Year: 2023,
    SubjectID: 314,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט וטכנולוגיה במיכון חקלאי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט ומנועי מטוסים': {
    Id: 2387,
    Year: 2023,
    SubjectID: 205,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט ומנועי מטוסים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט ותורת המנוע והרכב': {
    Id: 2460,
    Year: 2023,
    SubjectID: 294,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט ותורת המנוע והרכב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט טכני': {
    Id: 2452,
    Year: 2023,
    SubjectID: 280,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט טכני',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט מכונות': {
    Id: 2447,
    Year: 2023,
    SubjectID: 275,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט מכונות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט מנועי מטוסים ופרקי מכונו': {
    Id: 2389,
    Year: 2023,
    SubjectID: 207,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט מנועי מטוסים ופרקי מכונו',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט מערכות חשמל': {
    Id: 2392,
    Year: 2023,
    SubjectID: 210,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט מערכות חשמל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'סרטוט מפות': {
    Id: 2432,
    Year: 2023,
    SubjectID: 259,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'סרטוט מפות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ע"ג הוראה והדרכה': {
    Id: 2529,
    Year: 2023,
    SubjectID: 795,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ע"ג הוראה והדרכה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עבודת גמר': {
    Id: 2626,
    Year: 2023,
    SubjectID: 998,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עבודת גמר',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  עברית: {
    Id: 2322,
    Year: 2023,
    SubjectID: 11,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עברית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עולם הערבים והאיסלם': {
    Id: 2330,
    Year: 2023,
    SubjectID: 19,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עולם הערבים והאיסלם',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  עיצוב: {
    Id: 2617,
    Year: 2023,
    SubjectID: 891,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עיצוב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עיצוב אופנה ותלבושות': {
    Id: 2590,
    Year: 2023,
    SubjectID: 863,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עיצוב אופנה ותלבושות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עיצוב שיער וטיפוח החן': {
    Id: 2530,
    Year: 2023,
    SubjectID: 796,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עיצוב שיער וטיפוח החן',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב גרפי': {
    Id: 2591,
    Year: 2023,
    SubjectID: 864,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב גרפי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב המוצר': {
    Id: 2471,
    Year: 2023,
    SubjectID: 305,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב המוצר',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב התכשיט': {
    Id: 2592,
    Year: 2023,
    SubjectID: 865,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב התכשיט',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב וטכנולוגיה': {
    Id: 2470,
    Year: 2023,
    SubjectID: 304,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב וטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב חזותי': {
    Id: 2594,
    Year: 2023,
    SubjectID: 867,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב חזותי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב יהלומים': {
    Id: 2431,
    Year: 2023,
    SubjectID: 257,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב יהלומים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב כללי': {
    Id: 2595,
    Year: 2023,
    SubjectID: 868,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב כללי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב נוף': {
    Id: 2478,
    Year: 2023,
    SubjectID: 311,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב נוף',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'עצוב שיער קוסמטיקה ואיפור': {
    Id: 2593,
    Year: 2023,
    SubjectID: 866,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'עצוב שיער קוסמטיקה ואיפור',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  ערבית: {
    Id: 2329,
    Year: 2023,
    SubjectID: 18,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ערבית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ערבית ומורשת דרוזים': {
    Id: 2504,
    Year: 2023,
    SubjectID: 502,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ערבית ומורשת דרוזים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ערבית ותולדות הערבים והאסלם': {
    Id: 2497,
    Year: 2023,
    SubjectID: 494,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ערבית ותולדות הערבים והאסלם',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  פולנית: {
    Id: 2515,
    Year: 2023,
    SubjectID: 580,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'פולנית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  פורטוגזית: {
    Id: 2516,
    Year: 2023,
    SubjectID: 581,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'פורטוגזית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  פילוסופיה: {
    Id: 2351,
    Year: 2023,
    SubjectID: 40,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'פילוסופיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  פיסיקה: {
    Id: 2347,
    Year: 2023,
    SubjectID: 36,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'פיסיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  פסיכולוגיה: {
    Id: 2376,
    Year: 2023,
    SubjectID: 69,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'פסיכולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'פסיכולוגיה התפתחותית': {
    Id: 2597,
    Year: 2023,
    SubjectID: 870,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'פסיכולוגיה התפתחותית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  פרסית: {
    Id: 2517,
    Year: 2023,
    SubjectID: 582,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'פרסית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ציור טכסטיל': {
    Id: 2441,
    Year: 2023,
    SubjectID: 269,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ציור טכסטיל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'ציור שלטים ודקורציה': {
    Id: 2468,
    Year: 2023,
    SubjectID: 302,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'ציור שלטים ודקורציה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  צילום: {
    Id: 2598,
    Year: 2023,
    SubjectID: 871,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'צילום',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  "צ'כית": {
    Id: 2518,
    Year: 2023,
    SubjectID: 583,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: "צ'כית",
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  צרפתית: {
    Id: 2328,
    Year: 2023,
    SubjectID: 17,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'צרפתית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  קוסמטיקה: {
    Id: 2412,
    Year: 2023,
    SubjectID: 234,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'קוסמטיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'קרמיקה עצוב וטכנולוגיה': {
    Id: 2467,
    Year: 2023,
    SubjectID: 301,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'קרמיקה עצוב וטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'רבי מלל': {
    Id: 2627,
    Year: 2023,
    SubjectID: 999,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'רבי מלל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'רדיו ואלקטרוניקה ימית': {
    Id: 2602,
    Year: 2023,
    SubjectID: 875,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'רדיו ואלקטרוניקה ימית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  רומנית: {
    Id: 2449,
    Year: 2023,
    SubjectID: 584,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'רומנית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  רוסית: {
    Id: 2385,
    Year: 2023,
    SubjectID: 585,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'רוסית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'רשום ציור ואסטטיקה בעצוב': {
    Id: 2472,
    Year: 2023,
    SubjectID: 306,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'רשום ציור ואסטטיקה בעצוב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'שווק ומכירות': {
    Id: 2422,
    Year: 2023,
    SubjectID: 246,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'שווק ומכירות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'שיווק וקידום מכירות': {
    Id: 2603,
    Year: 2023,
    SubjectID: 876,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'שיווק וקידום מכירות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'שייט וניווט חופי': {
    Id: 2475,
    Year: 2023,
    SubjectID: 309,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'שייט וניווט חופי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תולדות האמנות והבנתה': {
    Id: 2427,
    Year: 2023,
    SubjectID: 252,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תולדות האמנות והבנתה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תולדות הלבוש וציורו': {
    Id: 2411,
    Year: 2023,
    SubjectID: 233,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תולדות הלבוש וציורו',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תולדות הערבית ואזרחות': {
    Id: 2502,
    Year: 2023,
    SubjectID: 500,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תולדות הערבית ואזרחות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תולדות עם ישראל': {
    Id: 2339,
    Year: 2023,
    SubjectID: 28,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תולדות עם ישראל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תולדות עם ישראל ואזרחות': {
    Id: 2498,
    Year: 2023,
    SubjectID: 495,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תולדות עם ישראל ואזרחות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  תורכית: {
    Id: 2519,
    Year: 2023,
    SubjectID: 586,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורכית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת הבנייה וחמרי בניין': {
    Id: 2439,
    Year: 2023,
    SubjectID: 266,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת הבנייה וחמרי בניין',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת החשמל': {
    Id: 2393,
    Year: 2023,
    SubjectID: 211,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת החשמל',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת הטלפון, תקשורת ומיתוג': {
    Id: 2396,
    Year: 2023,
    SubjectID: 214,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת הטלפון, תקשורת ומיתוג',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת המבנה, תחשיב ואוטומציה': {
    Id: 2425,
    Year: 2023,
    SubjectID: 250,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת המבנה, תחשיב ואוטומציה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת המדידה': {
    Id: 2433,
    Year: 2023,
    SubjectID: 260,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת המדידה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת הניווט הימי': {
    Id: 2605,
    Year: 2023,
    SubjectID: 878,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת הניווט הימי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת הסעוד': {
    Id: 2606,
    Year: 2023,
    SubjectID: 879,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת הסעוד',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת הצלום': {
    Id: 2430,
    Year: 2023,
    SubjectID: 256,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת הצלום',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת הקולנוע והטלויזיה': {
    Id: 2473,
    Year: 2023,
    SubjectID: 307,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת הקולנוע והטלויזיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תורת טכנאות השיניים': {
    Id: 2417,
    Year: 2023,
    SubjectID: 241,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תורת טכנאות השיניים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תושב"ע': {
    Id: 2316,
    Year: 2023,
    SubjectID: 5,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תושב"ע',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תושב"ע ומשפט עברי': {
    Id: 2318,
    Year: 2023,
    SubjectID: 7,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תושב"ע ומשפט עברי',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תחזוקת מערכות מכניות': {
    Id: 2528,
    Year: 2023,
    SubjectID: 792,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תחזוקת מערכות מכניות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תחזוקת מערכות סלולריות': {
    Id: 2633,
    Year: 2023,
    SubjectID: 781,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תחזוקת מערכות סלולריות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  תיאטרון: {
    Id: 2363,
    Year: 2023,
    SubjectID: 51,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תיאטרון',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  תיירות: {
    Id: 2607,
    Year: 2023,
    SubjectID: 880,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תיירות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תיירות ותפעול משרד נסיעות': {
    Id: 2423,
    Year: 2023,
    SubjectID: 247,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תיירות ותפעול משרד נסיעות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון הנדסי של מבנים': {
    Id: 2608,
    Year: 2023,
    SubjectID: 881,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון הנדסי של מבנים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון וסרטוט רהיטים': {
    Id: 2424,
    Year: 2023,
    SubjectID: 249,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון וסרטוט רהיטים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון ותכנות מערכות': {
    Id: 2394,
    Year: 2023,
    SubjectID: 212,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון ותכנות מערכות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון מבלטים ומתקנים': {
    Id: 2446,
    Year: 2023,
    SubjectID: 274,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון מבלטים ומתקנים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון פרקי מכונות': {
    Id: 2442,
    Year: 2023,
    SubjectID: 270,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון פרקי מכונות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון פרקי מכשירים': {
    Id: 2445,
    Year: 2023,
    SubjectID: 273,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון פרקי מכשירים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון צנרת ומבנים': {
    Id: 2444,
    Year: 2023,
    SubjectID: 272,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון צנרת ומבנים',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנון תפריט ומחסנאות': {
    Id: 2406,
    Year: 2023,
    SubjectID: 227,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנון תפריט ומחסנאות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכנות אוטוטק': {
    Id: 2655,
    Year: 2023,
    SubjectID: 773,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכנות אוטוטק',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תכשיטנות עצוב וטכנולוגיה': {
    Id: 2426,
    Year: 2023,
    SubjectID: 251,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תכשיטנות עצוב וטכנולוגיה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  תלמוד: {
    Id: 2317,
    Year: 2023,
    SubjectID: 6,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תלמוד',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תנ"ך': {
    Id: 2312,
    Year: 2023,
    SubjectID: 1,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תנ"ך',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תנ"ך וספרות': {
    Id: 2499,
    Year: 2023,
    SubjectID: 496,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תנ"ך וספרות',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תנ"ך ותושבע"פ': {
    Id: 2501,
    Year: 2023,
    SubjectID: 498,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תנ"ך ותושבע"פ',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תעשייה כימית': {
    Id: 2611,
    Year: 2023,
    SubjectID: 884,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תעשייה כימית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תעשיית המזון': {
    Id: 2612,
    Year: 2023,
    SubjectID: 885,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תעשיית המזון',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תפעול מלון': {
    Id: 2407,
    Year: 2023,
    SubjectID: 228,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תפעול מלון',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  תקשורת: {
    Id: 2630,
    Year: 2023,
    SubjectID: 56,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תקשורת',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תקשורת וחברה': {
    Id: 2641,
    Year: 2023,
    SubjectID: 788,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תקשורת וחברה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  תרמודינמיקה: {
    Id: 2365,
    Year: 2023,
    SubjectID: 54,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תרמודינמיקה',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תרמודינמיקה טכנית': {
    Id: 2613,
    Year: 2023,
    SubjectID: 886,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תרמודינמיקה טכנית',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
  'תשתיות מחשוב ותקשוב': {
    Id: 2642,
    Year: 2023,
    SubjectID: 794,
    ScientificInd: 'N',
    GeneralInd: 'N',
    SubjectNameHuji: 'תשתיות מחשוב ותקשוב',
    InsertDate: null,
    UpdateDate: null,
    User: null,
  },
}
